### ISSUE TITLE
Add getting started guide

### ISSUE THREAD

**Issue by anorsich** [paralect/react-starter#16]
It's not obvious that we need to run landing site in order to test koa-react-starter. Let's implement common ./bin/start.sh task as well as add a note about project dependencies.

**Comment by anorsich** [comment]
@ezhivitsa I was not able to easily test this PR. I think to stay consistent, we need to provide a guide for users on how to run this app, otherwise, it's hard to test/remember.

**Comment by bitwhys** [comment]
An update to the readme giving an explanation for the use of docker and the aforementioned start.sh script would probably suffice. As it stands it is slightly confusing on how to launch the project or what is critical or what can be removed. Thanks for the project none the less.
