### ISSUE TITLE
Lodash don't work as expected

### ISSUE THREAD

**Issue by AllDayAlone** [paralect/react-starter#71]
`mergeDeep` works as `merge`
`set` works only with array path
etc..

It's caused by LodashModuleReplacementPlugin

**Comment by maullerz** [comment]
With that plugin you should provide all needed feature-sets, because they are removed by default:
https://github.com/lodash/lodash-webpack-plugin#feature-sets

**Comment by hovoodd** [comment]
`LodashModuleReplacementPlugin` was removed from the starter.
